sonar.projectKey=nutnak-pipeline-backend-certif
sonar.projectName=nutnak-pipeline-backend-certif

sonar.sources=src
sonar.exclusions=src/__tests__/**

sonar.tests=src/__tests__
sonar.test.inclusions=src/__tests__/**/*.test.ts

sonar.javascript.lcov.reportPaths=coverage/lcov.info
